### ISSUE TITLE
Source being null prevents library sync

### ISSUE THREAD

**Issue by Nightchanger** [andrew-codes/playnite-web#659]
![image](https://github.com/user-attachments/assets/914ed7ba-706a-4395-93e0-36912fff2b94)

**Comment by andrew-codes** [comment]
What sources do you have in your Playnite library? You can check the extension.log file to see if any errors were logged by the plugin. The extenions.log file can be found in Playnite's application directory.

**Comment by andrew-codes** [comment]
I think there is a legitimate error in the plugin that was recently introduced. I thought it was introduced and then resolved, but this does not appear to be the case.

For more context: a game's source may not always be set within Playnite. This is often the case with emulators or manually added games. In the case a source is not set, it defaults to Emulator as the source and creates this new source on the fly to be used (as it is not in Playnite proper). This is why I thought it was resolved by using a default "Emulator" source when the underlying value is null.

I'll have to investigate this further to see where this is breaking down. I certainly think it is a bug in the plugin.

**Comment by Shayviri** [comment]
When I have the error, I do not see any error in the extension.log file. However, in the playnite.log file I have this:
|ERROR|MainMenu:Main menu extension action failed.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PlayniteWeb.Models.Game.<>c.<GetReleases>b__21_0(Game g) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Models\Game.cs:line 57
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PlayniteWeb.Models.Game.<GetReleases>d__21.MoveNext() in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Models\Game.cs:line 57
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PlayniteWeb.Models.Game..ctor(IEnumerable`1 playniteGames, IEnumerable`1 defaultPlatforms, GameSource defaultSource) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Models\Game.cs:line 41
   at PlayniteWeb.PlayniteWeb.<>c__DisplayClass36_0.<SyncLibrary>b__1(IGrouping`2 groupedByName) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 198
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PlayniteWeb.PlayniteWeb.SyncLibrary() in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 198
   at PlayniteWeb.PlayniteWeb.SyncLibraryFromMenu(MainMenuItemActionArgs args) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 188

sorry for the format but there are some " ` " in the error that make this weird formating 

I don't know if this helps

**Comment by andrew-codes** [comment]
This is very helpful! Thank you!

**Comment by Shayviri** [comment]
I updated my docker with the :dev tag and installed the plugin you gave (v4.0.2). And I still have the same error:

|ERROR|MainMenu:Main menu extension action failed.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at PlayniteWeb.Models.Game.get_Name() dans D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Models\Game.cs:line 31
   at PlayniteWeb.Models.Game.<GetReleases>d__22.MoveNext() in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Models\Game.cs:line 67
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PlayniteWeb.Models.Game..ctor(IEnumerable`1 playniteGames, IEnumerable`1 defaultPlatforms, GameSource defaultSource) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\Models\Game.cs:line 44
   at PlayniteWeb.PlayniteWeb.<>c__DisplayClass36_0.<SyncLibrary>b__1(IGrouping`2 groupedByName) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 200
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PlayniteWeb.PlayniteWeb.SyncLibrary() in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 200
   at PlayniteWeb.PlayniteWeb.SyncLibraryFromMenu(MainMenuItemActionArgs args) in D:\a\playnite-web\playnite-web\apps\PlayniteWebPlugin\src\PlayniteWeb.cs:line 188
   at Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass17_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\MainMenu.cs:line 380

I am sorry, I think the last line was missing in the previous error I gave you

**Comment by andrew-codes** [comment]
This is very helpful. The second error is at a different location in the code and gives me a new lead. I apologize for having you be the tester. I can't reproduce it locally and don't what data in Playnite is required to reproduce it. I'll follow up soon with a new builds to try. Thanks again!

**Comment by andrew-codes** [comment]
@Shayviri , @Nightchanger , try the latest dev app and this Plugin version: https://github.com/andrew-codes/playnite-web/actions/runs/12243037521/artifacts/2295901727. Drop the database, retry, and report back. You may see more logs if there are any games that cannot be processed. Before it may have errored out, now it will produce a warning in the extension.log file. Thanks!

**Comment by Shayviri** [comment]
Hi, I tried with the new plugin and the latest dev app, and it worked!
I checked the extension log and indeed there are warnings for some games like:
|WARN |PlayniteWeb#Game:Game Minecraft All the Mods 10 - ATM10 has no source. These will be published with the source Emulator.

**Comment by andrew-codes** [comment]
That's great news! 😁 I'll close this issue and cut a release.
